version: '3.7'
networks:
  laravel-network:
    internal: false
volumes:
  laravelMysqlVolume:
    external: true
services:
  backend:
    image: action-learning
    depends_on:
      - mysql
    networks:
      - laravel-network
    ports:
      - target: 8081
        published: 84
        protocol: tcp
        mode: host
    environment:
      - APP_ENV=dev
      - APP_SECRET=thisisnotasecret
      - APP_DEBUG=true
      - DATABASE_URL=mysql://app_user:982hhfn9i24ugh925hg9235thrg39w28014t08hij@laravel-mysql:3306/laravel_db
    build:
      context: .
      network: host
    volumes:
      - type: bind
        source: .
        target: /var/www/html
  mysql:
    container_name: laravel-mysql
    networks:
      - laravel-network
    image: mysql:8.0.28
    environment:
      MYSQL_ROOT_PASSWORD: Lift-extract-anthony-92
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: 982hhfn9i24ugh925hg9235thrg39w28014t08hij
    ports:
      - "3308:3307"
    expose:
      - '3308'
    # volumes:
      # - laravelMysqlVolume:/var/lib/mysql

  adminer:
    container_name: adminer_php
    networks:
      - laravel-network
    image: adminer
    ports:
      - "8082:8080"
